sudo: false
language: node_js
before_install:
  - npm install npm -g
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
matrix:
  include:
    - node_js: "8"
      env: TEST_SUITE=coverage
    - node_js: "8"
      env: TEST_SUITE=lint
env:
  - TEST_SUITE=test
script: npm run-script $TEST_SUITE
